services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMODB_TABLE_NAME=items
      - S3_BUCKET_NAME=my-unique-bucket-name
    depends_on:
      # Waits for the localstack container to be healthy before starting
      localstack:
        condition: service_healthy

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=dynamodb,s3
      - EAGER_SERVICE_LOADING=1
    volumes:
      - ./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    healthcheck:
      # This command is proven to work and waits for DynamoDB to be available
      test: ["CMD", "awslocal", "dynamodb", "list-tables"]
      interval: 5s
      timeout: 10s
      retries: 10

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      # Provides the API endpoint to the test suite
      - API_BASE_URL=http://api:5000
    depends_on:
      - api